<a href="https://colab.research.google.com/github/viveksharma-niet/Tensor/blob/main/TensorFlow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Topics to be covered in this session:

1. How to create tensors?
2. Two ways of declaring tensors
3. Mathematical Operations
4. Linear Algebra

### Following topics are covered in the optional session titled: 'Advanced Operations with TensorFlow'

5. Reshaping and Broadcasting
6. Automatic Differentiation

In [ ]:
import tensorflow as tf
import numpy as np

### 1. Tensors of different ranks

In [ ]:
"""A vector is a 1-dimensional tensor"""

# Vector in TensorFlow
vector_tf = tf.constant([0, 1, 2, 3, 4])

# Vector in Numpy
vector_np = np.array([0, 1, 2, 3, 4])

print("Shapes:", vector_tf.shape, vector_np.shape)

""" A matrix is a 2-dimensional tensor"""

# Matrix in TensorFlow
matrix_tf = tf.constant([[0, 1], [2, 3], [4, 5]])

# Matrix in Numpy
matrix_np = np.array([[0, 1], [2, 3], [4, 5]])

print("Shapes:", matrix_tf.shape, matrix_np.shape)

"""3-dimensional tensor"""

# 3-d tensor in TensorFlow
t3_tf = tf.constant([[[0., 1.], [2, 3], [4, 5]]]*5)

# 3-d matrix in Numpy
t3_np = np.array([[[0, 1], [2, 3], [4, 5]]]*5)

print("Shapes:", t3_tf.shape, t3_np.shape)

Shapes: (5,) (5,)
Shapes: (3, 2) (3, 2)
Shapes: (5, 3, 2) (5, 3, 2)


In [ ]:
print(t3_tf)

tf.Tensor(
[[[0. 1.]
  [2. 3.]
  [4. 5.]]

 [[0. 1.]
  [2. 3.]
  [4. 5.]]

 [[0. 1.]
  [2. 3.]
  [4. 5.]]

 [[0. 1.]
  [2. 3.]
  [4. 5.]]

 [[0. 1.]
  [2. 3.]
  [4. 5.]]], shape=(5, 3, 2), dtype=float32)


##Question##

Declare a tensor of shape (2,2,2,2) with random numbers from normal distribution whose mean is 1 and the standard deviation is also 1.


In [ ]:
# approach 1 - initialize the nd array in Numpy and then use that to initialize the tensor
arr = np.random.randn(2,2,2,2) # returns random numbers from standard normal distribution - mean = 0, std = 1
print(arr.shape)
print(arr)

arr = arr + 1 # adding 1 makes the random numbers from normal distribtuion which has mean = 1

# to change the standard deviation as well as multiply with the new standard deviation, std = 2.5
# arr = 2.5 * arr + 1

arr_tf = tf.constant(arr)
print(arr_tf)

print(type(arr_tf.numpy()))

(2, 2, 2, 2)
[[[[ 1.22962444  1.42005364]
   [-0.44236402  0.44317297]]

  [[ 0.50054353 -0.31532713]
   [-1.55384478 -0.63380277]]]


 [[[-2.43461537  0.54048916]
   [-0.2299195   0.16563244]]

  [[ 0.13099296 -0.38535683]
   [ 1.51523052  0.9540981 ]]]]
tf.Tensor(
[[[[ 2.22962444  2.42005364]
   [ 0.55763598  1.44317297]]

  [[ 1.50054353  0.68467287]
   [-0.55384478  0.36619723]]]


 [[[-1.43461537  1.54048916]
   [ 0.7700805   1.16563244]]

  [[ 1.13099296  0.61464317]
   [ 2.51523052  1.9540981 ]]]], shape=(2, 2, 2, 2), dtype=float64)
<class 'numpy.ndarray'>


In [ ]:
# approach 2 - using random number genrating functions from TensorFlow
arr_tf = tf.random.normal((2,2,2,2), mean=1, stddev=1, name="my_tensor")
print(arr_tf.shape)
print(arr_tf.numpy())

(2, 2, 2, 2)
[[[[ 1.7524806   2.3402848 ]
   [ 0.42945445  2.1026502 ]]

  [[ 0.84322655  1.9451708 ]
   [-0.63544583 -0.11136401]]]


 [[[ 2.2880816   0.08688265]
   [ 2.9293427   1.3310047 ]]

  [[ 1.2040068   0.46884692]
   [ 1.1152604   0.4716217 ]]]]


### 2. Two ways of declaring tensors

In [ ]:
"""Two types of tensors: tf.constant & tf.Variable"""
const_tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
var_tensor = tf.Variable([[1, 2, 3], [4, 5, 6]])

In [ ]:
"""Declaring tensors with specific datatypes"""
int32_tensor = tf.Variable([[1, 2, 3], [4, 5, 6]], dtype=tf.int32) # specify int32 datatype
float32_tensor = tf.Variable([[1, 2, 3], [4, 5, 6]], dtype=tf.float32) # specify float32 datatype
bool_tensor = tf.Variable([True, False, False], dtype=tf.bool) # specify bool datatype.

print("Int32 tensor:", int32_tensor)
print("Float32 tensor:", float32_tensor)
print("Boolean tensor:", bool_tensor)

Int32 tensor: <tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>
Float32 tensor: <tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>
Boolean tensor: <tf.Variable 'Variable:0' shape=(3,) dtype=bool, numpy=array([ True, False, False])>


In [ ]:
int32_tensor.numpy()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

#### Note that tf.Variable infers the datatype if it is not specified. Hence the bool tensor could have been declared as
#### bool_tensor = tf.Variable([True, False, False])
#### and the result would have been same.

### 3. Common mathematical operations on tensors

In [ ]:
"""Let us define two tensors"""

x = tf.Variable([list(range(5))]*5) # 2D tensor of shape (5, 5)
y = tf.Variable([list(range(5, 10))]*5) # 2D tensor of shape (5, 5)

print("x:", x)
print("y:", y)

x: <tf.Variable 'Variable:0' shape=(5, 5) dtype=int32, numpy=
array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]], dtype=int32)>
y: <tf.Variable 'Variable:0' shape=(5, 5) dtype=int32, numpy=
array([[5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9]], dtype=int32)>


In [ ]:
"""Simple mathematical operations two tensors"""
z = x + y # element-wise addition
print("z:", z)

w = x * y # element-wise multiplications
print("w:", w)

v = y / x # element-wise division does not raise exception for division by 0 as TensorFlow supports Inf and NaN types
print("v:", v)

z: tf.Tensor(
[[ 5  7  9 11 13]
 [ 5  7  9 11 13]
 [ 5  7  9 11 13]
 [ 5  7  9 11 13]
 [ 5  7  9 11 13]], shape=(5, 5), dtype=int32)
w: tf.Tensor(
[[ 0  6 14 24 36]
 [ 0  6 14 24 36]
 [ 0  6 14 24 36]
 [ 0  6 14 24 36]
 [ 0  6 14 24 36]], shape=(5, 5), dtype=int32)
v: tf.Tensor(
[[       inf 6.         3.5        2.66666667 2.25      ]
 [       inf 6.         3.5        2.66666667 2.25      ]
 [       inf 6.         3.5        2.66666667 2.25      ]
 [       inf 6.         3.5        2.66666667 2.25      ]
 [       inf 6.         3.5        2.66666667 2.25      ]], shape=(5, 5), dtype=float64)


#### Alternatively, use TensorFlow functions for the mathematical operations
#### z = tf.add(x, y)
#### w = tf.multiply(x, y)
#### v = tf.divide(y, x)

#### Note that element-wise operations does not work if tensors have different shapes or cannot be broadcasted

In [ ]:
# transpose of tensors
y = tf.Variable([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11], [12, 13, 14]]) # shape is (5, 3)
z = tf.transpose(y) # shape is (3, 5)
print("Before transpose:", y)
print("After transpose:", z)

Before transpose: <tf.Variable 'Variable:0' shape=(5, 3) dtype=int32, numpy=
array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]], dtype=int32)>
After transpose: tf.Tensor(
[[ 0  3  6  9 12]
 [ 1  4  7 10 13]
 [ 2  5  8 11 14]], shape=(3, 5), dtype=int32)


###     
### 4. Linear algebra on tensors

In [ ]:
# Matrix multiplication
x = tf.Variable([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14], [15, 16, 17, 18, 19], [20, 21, 22, 23, 24]])
y = tf.Variable([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11], [12, 13, 14]])

z = tf.linalg.matmul(x, y) # matrix multiplication between a (5, 5) and a (5, 3) tensor
print("z:", z)

z: tf.Tensor(
[[ 90 100 110]
 [240 275 310]
 [390 450 510]
 [540 625 710]
 [690 800 910]], shape=(5, 3), dtype=int32)


#### Note that tf.linalg.matmul raises exception if tensor shapes are incompatible for matrix multiplication

In [ ]:
# Matrix inverse
try:
    x = tf.Variable([[2, 3], [2, 2]])
    xinv = tf.linalg.inv(x)
    print("Inverse of x:", xinv)
except Exception as e:
    print("Exception raised while performing tensor inverse:\n", str(e))

Exception raised while performing tensor inverse:
 Value for attr 'T' of int32 is not in the list of allowed values: double, float, half, complex64, complex128
	; NodeDef: {{node MatrixInverse}}; Op<name=MatrixInverse; signature=input:T -> output:T; attr=adjoint:bool,default=false; attr=T:type,allowed=[DT_DOUBLE, DT_FLOAT, DT_HALF, DT_COMPLEX64, DT_COMPLEX128]> [Op:MatrixInverse] name: 


#### The above exception occured because matrix inverse is allowed only for float datatypes (float16, float 32 etc.). The try-except block
#### is purposefully used to demonstrate this behaviour.

In [ ]:
# Let us try after changing the datatype using tf.cast function
x = tf.cast(x, tf.float32)
xinv = tf.linalg.inv(x)
print("Inverse of x:", xinv)

Inverse of x: tf.Tensor(
[[-1.   1.5]
 [ 1.  -1. ]], shape=(2, 2), dtype=float32)


#### Note that if the matrix is not invertible tf.linalg.inv will raise an exception

In [ ]:
# Eigen value decomposition
x = tf.Variable([[3, 2, 4], [2, 0, 2], [4, 2, 3]], dtype=tf.float32) # raises exception if datatype is not floatX
eigen_values, eigen_vectors = tf.linalg.eigh(x)
print("Eigen values:", eigen_values)
print("Eigen vectors:", eigen_vectors)

Eigen values: tf.Tensor([-1.0000004 -0.9999995  8.       ], shape=(3,), dtype=float32)
Eigen vectors: tf.Tensor(
[[-0.74535596  0.          0.66666675]
 [ 0.2981424  -0.8944272   0.33333328]
 [ 0.59628487  0.4472136   0.6666666 ]], shape=(3, 3), dtype=float32)


##Question##

Solve the following system of linear equations using TensorFlow:

x + y + z + w = 13

2x + 3y − w = −1

−3x + 4y + z + 2w = 10

x + 2y − z + w = 1

Ans: x = 2, y = 0, z = 6 , w = 5

In [ ]:
coeff = tf.Variable([[1,1,1,1], [2,3,0,-1], [-3,4,1,2], [1,2,-1,1]], dtype=tf.float32) # W
print("Coeff:", coeff)

y = tf.Variable([[13], [-1], [10], [1]], dtype=tf.float32)
print("y:", y)

# x = inverse of coeff X y

inv_coeff = tf.linalg.inv(coeff)
print("Inverse of coeff:", inv_coeff)

x_solution = tf.matmul(inv_coeff, y)
print(x_solution)


Coeff: <tf.Variable 'Variable:0' shape=(4, 4) dtype=float32, numpy=
array([[ 1.,  1.,  1.,  1.],
       [ 2.,  3.,  0., -1.],
       [-3.,  4.,  1.,  2.],
       [ 1.,  2., -1.,  1.]], dtype=float32)>
y: <tf.Variable 'Variable:0' shape=(4, 1) dtype=float32, numpy=
array([[13.],
       [-1.],
       [10.],
       [ 1.]], dtype=float32)>
Inverse of coeff: tf.Tensor(
[[ 2.77777791e-01  5.55555224e-02 -1.66666672e-01  1.11111104e-01]
 [-7.40740746e-02  1.85185164e-01  1.11111104e-01  3.70370336e-02]
 [ 4.62962925e-01  9.25926119e-02  5.55555634e-02 -4.81481493e-01]
 [ 3.33333343e-01 -3.33333343e-01 -9.93410776e-09  3.33333343e-01]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[ 2.0000000e+00]
 [-1.0058284e-07]
 [ 5.9999995e+00]
 [ 5.0000005e+00]], shape=(4, 1), dtype=float32)


####**The following topics have been covered in the optional session : 'Advanced Operations with Tensorflow.'**

### 5. Reshaping and Broadcasting

#### 5.1. Reshaping

In [ ]:
# Reshaping changes the dimensions or axes and assigns the cell values in proper locations in the new tensor
x = tf.Variable([[-3, 2, 4], [2, 0, -2], [5, 2, 3]], dtype=tf.float32)
print("Initial tensor:", x)
x_reshaped = tf.reshape(x, shape=(9, 1)) # a (3, 3) tensor can be reshaped to (9, 1) amd (1, 9) tensors only
print("Reshaped tensor:", x_reshaped)

Initial tensor: <tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[-3.,  2.,  4.],
       [ 2.,  0., -2.],
       [ 5.,  2.,  3.]], dtype=float32)>
Reshaped tensor: tf.Tensor(
[[-3.]
 [ 2.]
 [ 4.]
 [ 2.]
 [ 0.]
 [-2.]
 [ 5.]
 [ 2.]
 [ 3.]], shape=(9, 1), dtype=float32)


In [ ]:
# tf.reshape raises exception if the new shape is incompatible
try:
    x_reshape = tf.reshape(x, shape=(3, 4))
except Exception as e:
    print("Exception raised while reshaping:\n", str(e))

Exception raised while reshaping:
 {{function_node __wrapped__Reshape_device_/job:localhost/replica:0/task:0/device:CPU:0}} Input to reshape is a tensor with 9 values, but the requested shape has 12 [Op:Reshape]


#### 5.2. Broadcasting

##### Mathematical operations on tensors requires shape compatibility otherwise exception is raised. However, broadcasting can resolve shape incompatibilities in few situations. Let us see an example.

In [ ]:
x = tf.Variable([[3, 2, 4], [2, 0, 2], [4, 2, 3]], dtype=tf.float32)
k = tf.Variable([2.1])

print("Shape of x:", x.shape)
print("Shape of k:", k.shape)

# element-wise multiplication by broadcasting which repeats the only element in k along both the axes
# to resolve the shape imcompatibility
y = x * k
print("Shape of y:", y)

Shape of x: (3, 3)
Shape of k: (1,)
Shape of y: tf.Tensor(
[[6.2999997 4.2       8.4      ]
 [4.2       0.        4.2      ]
 [8.4       4.2       6.2999997]], shape=(3, 3), dtype=float32)


In [ ]:
# Let us see another example
k = tf.Variable([2.1, 3.0, -1.4])

# in this case broadcasting repeats [2.1, 3.0, -1.4] three times along the row to make the shapes compatible
y = x * k
print("y:", y)

y: tf.Tensor(
[[ 6.2999997  6.        -5.6      ]
 [ 4.2        0.        -2.8      ]
 [ 8.4        6.        -4.2      ]], shape=(3, 3), dtype=float32)


In [ ]:
# Broadcasting of rank 2 tensor for multiplying with rank 3 tensor

# Rank 2 tensor to be broadcasted
k = tf.Variable([[2.1, 3.0, -1.4], [1.1, 3.2, -1.1], [0.67, 2.1, -0.03]])

# Rank 3 tensor
x = tf.Variable([[[3, 2, 4],
                  [2, 0, 2],
                  [4, 2, 3]],
                 [[0, -2, 1],
                  [4, 0, 2],
                  [6, -2, 3]]
                 ], dtype=tf.float32)

# Here shape of x is (2, 3, 3) and that of k is (3, 3). Hence broadcasting will add a new axes and repeat k along it.
y = x * k
print("y:", y)

y: tf.Tensor(
[[[ 6.2999997  6.        -5.6      ]
  [ 2.2        0.        -2.2      ]
  [ 2.68       4.2       -0.09     ]]

 [[ 0.        -6.        -1.4      ]
  [ 4.4        0.        -2.2      ]
  [ 4.02      -4.2       -0.09     ]]], shape=(2, 3, 3), dtype=float32)


In [ ]:
# Alternatively, we can add the new dimension before multiplying
print("Old shape:", k.shape)
k = tf.expand_dims(k, axis=0) # insert a new axis along the first dimension to create a rank 3 tensor
print("New shape:", k.shape)

y = x * k
print("y:", y)

Old shape: (3, 3)
New shape: (1, 3, 3)
y: tf.Tensor(
[[[ 6.2999997  6.        -5.6      ]
  [ 2.2        0.        -2.2      ]
  [ 2.68       4.2       -0.09     ]]

 [[ 0.        -6.        -1.4      ]
  [ 4.4        0.        -2.2      ]
  [ 4.02      -4.2       -0.09     ]]], shape=(2, 3, 3), dtype=float32)


### 6. Automatic Differentiation

#### Gradients or partial derivatives are useful for training linear models and neural networks using gradient-based optimization
#### TensorFlow's tf.GradientTape records computations and computes gradients in reverse-mode differentiation.
#### Let us see how it works.

####  
#### 6.1 How to use tf.GradientTape?

In [ ]:
# declare tensor for with respect to which gradient is required
x = tf.Variable(3.0)

# using tf.GradientTape context to perform computations and record them in tape
with tf.GradientTape() as tape:
    y = 3.0 * tf.math.log(x)

# compute gradients
dy_dx = tape.gradient(y, x) # for y = log(x), dy/dx = 1/x
print("Gradient dy_dx:", dy_dx) # alternately doing dy_dx.numpy() returns the result as a numpy array which in this case is a single value

Gradient dy_dx: tf.Tensor(1.0, shape=(), dtype=float32)


In [ ]:
# for multi-variate functions, gradients are partial derivatives
x = tf.Variable(3.0)
y = tf.Variable(4.0)

with tf.GradientTape() as tape:
    r = x**2 + y**2

dr_dx, dr_dy = tape.gradient(r, [x, y]) # the first argument is the target function and the second one is a list of variables
print("dr_dx:", dr_dx.numpy()) # ∂r/∂x = 2x
print("dr_dy:", dr_dy.numpy()) # ∂r/∂y = 2y

dr_dx: 6.0
dr_dy: 8.0


In [ ]:
# tf.GradientTape supports the Chain Rule of Differentiation as well
x = tf.Variable(3.0)

with tf.GradientTape() as tape:
    y = x ** 2 # y is a function of x
    r = y ** 2 # r is a function of y

dr_dx = tape.gradient(r, x) # Chain rule is applied to compute dr_dx as r is a function of x through y
print("dr_dx:", dr_dx.numpy()) # dr/dx = dr/dy × dy/dx = 2y × 2x = 2(x²) × 2x = 4x³

dr_dx: 108.0


#### Note that the intermediate variable 'y' is released outside the context of tf.GradientTape. To compute gradient dr/dy, tf.GradientTape
#### needs to be persistent

In [ ]:
# Persistent tf.GradientTape
x = tf.Variable(3.0)

with tf.GradientTape(persistent=True) as tape:
    y = x ** 2
    r = y ** 2

dr_dx = tape.gradient(r, x)
dr_dy = tape.gradient(r, y)

print("dr_dx:", dr_dx.numpy())
print("dr_dy:", dr_dy.numpy())

dr_dx: 108.0
dr_dy: 18.0


####  
#### 6.2 How to use tf.GradientTape for model training?

In [ ]:
# Let us see this in action in the context of Logistic Regression

# Points to note:
# 1. For logistic regression, the probabilty P(y=1|X) = 1/[1+exp{-(WX+b)}]; where W & b are weights and bias of the model
# 2. The loss function is L = -ylog[P(y=1|X)] - (1-y)log[1-P(y=1|X)] otherwise known as binary log loss.
# 3. For training the model using Stochastic Gradient Descent, we need to compute ∂L/∂W and ∂L/∂b.

# Let us see how we can compute the gradients using tf.GradientTape

In [ ]:
# declare weights and bias of the model
num_features = 10 # the model has 10 features
W = tf.Variable(tf.random.normal(shape=(10, ))) # wrapping the random numbers with tf.Variable to enable gradients on W
b = tf.Variable(tf.random.normal(shape=(1, )))  # wrapping the random numbers with tf.Variable to enable gradients on b

# let us initialize a training samples
num_samples = 100

# generate training samples randomly and wrap them up in tf.constant to disable gradient computation on samples
X = tf.constant(tf.random.uniform(shape=(100, 10)))
y = tf.constant(tf.cast(tf.greater(tf.random.uniform(shape=(100,)), 0.80), dtype=tf.float32)) # target must be 0 and 1

In [ ]:
# compute gradients
with tf.GradientTape() as tape:
    log_odds = tf.reduce_sum(W * X, axis=1) + b
    # tf.reduce_sum(W * X, axis=1) results in a (1, ) vector to which b is added

    probas = tf.sigmoid(log_odds) # using sigmoid function available in TensorFlow

    loss = tf.reduce_mean(-y*tf.math.log(probas) -(1.-y)*tf.math.log(1.-probas))

[dloss_dW, dloss_db]  = tape.gradient(loss, [W, b])

print("dloss_dW:", dloss_dW.numpy())
print("dloss_db:", dloss_db.numpy())

dloss_dW: [0.3393902  0.31333876 0.28984714 0.37596196 0.33388257 0.3055682
 0.33240983 0.3137926  0.34068426 0.3184052 ]
dloss_db: [0.6390459]


####  
#### 6.3 How to disable gradient computation for selected variables?

In [ ]:
# let us use an earlier example to show how to disable gradient computation
# for multi-variate functions, gradients are partial derivatives
x = tf.Variable(3.0, trainable=True)  # by default, trainable=True so we did npt mention it earlier
y = tf.Variable(4.0, trainable=False) # trainable=False signals tf.GradientTape to stop tracking the variable

with tf.GradientTape() as tape:
    r = x**2 + y**2

try:
    dr_dx, dr_dy = tape.gradient(r, [x, y])
    print("dr_dx:", dr_dx.numpy())
    print("dr_dy:", dr_dy.numpy()) # dr_dy is None hence this line would raise an exception
except Exception as e:
    print("Error occurred during gradient computation:\n", str(e))

dr_dx: 6.0
Error occurred during gradient computation:
 'NoneType' object has no attribute 'numpy'
